//!  | **Instructie** | **Implied** | **Immediate** | **Accumulator** | **Absolute** | **Absolute,X** | **Absolute,Y** | **Zero Page** | **Zero Page,X** | **Indirect** | **Indirect,X** | **Indirect,Y** |
//! |----------------|-------------|---------------|-----------------|--------------|----------------|----------------|---------------|-----------------|--------------|----------------|----------------|
//! | ADC           |             | 69            |                 | 6D           | 7D             | 79             | 65            | 75             |              | 61             | 71             |
//! | AND           |             | 29            |                 | 2D           | 3D             | 39             | 25            | 35             |              | 21             | 31             |
//! | ASL           |             |               | 0A              | 0E           | 1E             |                | 06            | 16             |              |                |                |
//! | BCC           | 90          |               |                 |              |                |                |               |                 |              |                |                |
//! | BCS           | B0          |               |                 |              |                |                |               |                 |              |                |                |
//! | BEQ           | F0          |               |                 |              |                |                |               |                 |              |                |                |
//! | BIT           |             |               |                 | 2C           |                |                | 24            |                 |              |                |                |
//! | BMI           | 30          |               |                 |              |                |                |               |                 |              |                |                |
//! | BNE           | D0          |               |                 |              |                |                |               |                 |              |                |                |
//! | BPL           | 10          |               |                 |              |                |                |               |                 |              |                |                |
//! | BRK           | 00          |               |                 |              |                |                |               |                 |              |                |                |
//! | BVC           | 50          |               |                 |              |                |                |               |                 |              |                |                |
//! | BVS           | 70          |               |                 |              |                |                |               |                 |              |                |                |
//! | CLC           | 18          |               |                 |              |                |                |               |                 |              |                |                |
//! | CLD           | D8          |               |                 |              |                |                |               |                 |              |                |                |
//! | CLI           | 58          |               |                 |              |                |                |               |                 |              |                |                |
//! | CLV           | B8          |               |                 |              |                |                |               |                 |              |                |                |
//! | CMP           |             | C9            |                 | CD           | DD             | D9             | C5            | D5             |              | C1             | D1             |
//! | CPX           |             | E0            |                 | EC           |                |                | E4            |                 |              |                |                |
//! | CPY           |             | C0            |                 | CC           |                |                | C4            |                 |              |                |                |
//! | DEC           |             |               |                 | CE           | DE             |                | C6            | D6             |              |                |                |
//! | DEX           | CA          |               |                 |              |                |                |               |                 |              |                |                |
//! | DEY           | 88          |               |                 |              |                |                |               |                 |              |                |                |
//! | EOR           |             | 49            |                 | 4D           | 5D             | 59             | 45            | 55             |              | 41             | 51             |
//! | INC           |             |               |                 | EE           | FE             |                | E6            | F6             |              |                |                |
//! | INX           | E8          |               |                 |              |                |                |               |                 |              |                |                |
//! | INY           | C8          |               |                 |              |                |                |               |                 |              |                |                |
//! | JMP           |             |               |                 | 4C           |                |                |               |                 | 6C           |                |                |
//! | JSR           |             |               |                 | 20           |                |                |               |                 |              |                |                |
//! | LDA           |             | A9            |                 | AD           | BD             | B9             | A5            | B5             |              | A1             | B1             |
//! | LDX           |             | A2            |                 | AE           |                | BE             | A6            |                 |              |                |                |
//! | LDY           |             | A0            |                 | AC           | BC             |                | A4            | B4             |              |                |                |
//! | LSR           |             |               | 4A              | 4E           | 5E             |                | 46            | 56             |              |                |                |
//! | NOP           | EA          |               |                 |              |                |                |               |                 |              |                |                |
//! | ORA           |             | 09            |                 | 0D           | 1D             | 19             | 05            | 15             |              | 01             | 11             |
//! | PHA           |             |               | 48              |              |                |                |               |                 |              |                |                |
//! | PHP           | 08          |               |                 |              |                |                |               |                 |              |                |                |
//! | PLA           |             |               | 68              |              |                |                |               |                 |              |                |                |
//! | PLP           | 28          |               |                 |              |                |                |               |                 |              |                |                |
//! | ROL           |             |               | 2A              | 2E           | 3E             |                | 26            | 36             |              |                |                |
//! | ROR           |             |               | 6A              | 6E           | 7E             |                | 66            | 76             |              |                |                |
//! | RTI           | 40          |               |                 |              |                |                |               |                 |              |                |                |
//! | RTS           | 60          |               |                 |              |                |                |               |                 |              |                |                |
//! | SBC           |             | E9            |                 | ED           | FD             | F9             | E5            | F5             |              | E1             | F1             |
//! | SEC           | 38          |               |                 |              |                |                |               |                 |              |                |                |
//! | SED           | F8          |               |                 |              |                |                |               |                 |              |                |                |
//! | SEI           | 78          |               |                 |              |                |                |               |                 |              |                |                |
//! | STA           |             |               |                 | 8D           | 9D             | 99             | 85            | 95             |              | 81             | 91             |

pub type OpCode = u8;
const UNUSED: OpCode = 0xFF;
pub const NO_IMPLIED: OpCode = UNUSED;
pub const NO_IMMEDIATE: OpCode = UNUSED;
pub const NO_ACCUMULATOR: OpCode = UNUSED;
pub const NO_ABSOLUTE: OpCode = UNUSED;
pub const NO_ABSOLUTE_X: OpCode = UNUSED;
pub const NO_ABSOLUTE_Y: OpCode = UNUSED;
pub const NO_ZEROPAGE: OpCode = UNUSED;
pub const NO_ZEROPAGE_X: OpCode = UNUSED;
pub const NO_ZEROPAGE_Y: OpCode = UNUSED;
pub const NO_INDIRECT: OpCode = UNUSED;
pub const NO_INDEXED_INDIRECT: OpCode = UNUSED;
pub const NO_INDIRECT_INDEXED: OpCode = UNUSED;
pub const NO_RELATIVE: OpCode = UNUSED;

pub struct InstructionDef {
    pub instruction: &'static str,
    pub implied: OpCode,
    pub immediate: OpCode,
    pub accumulator: OpCode,
    pub absolute: OpCode,
    pub absolute_x: OpCode,
    pub absolute_y: OpCode,
    pub zeropage: OpCode,
    pub zeropage_x: OpCode,
    pub zeropage_y: OpCode,
    pub relative: OpCode,
    pub indirect: OpCode,
    pub indexed_indirect: OpCode,
    pub indirect_indexed: OpCode,
}
impl InstructionDef {
    fn new(
        instruction: &'static str,
        implied: OpCode,
        immediate: OpCode,
        accumulator: OpCode,
        absolute: OpCode,
        absolute_x: OpCode,
        absolute_y: OpCode,
        zeropage: OpCode,
        zeropage_x: OpCode,
        zeropage_y: OpCode,
        relative: OpCode,
        indirect: OpCode,
        indexed_indirect: OpCode,
        indirect_indexed: OpCode,
    ) -> InstructionDef {
        InstructionDef {
            instruction,
            implied,
            immediate,
            accumulator,
            absolute,
            absolute_x,
            absolute_y,
            zeropage,
            zeropage_x,
            zeropage_y,
            relative,
            indirect,
            indexed_indirect,
            indirect_indexed,
        }
    }
}

pub fn isa_6502() -> Vec<InstructionDef> {
    vec![
        InstructionDef::new(
            "adc",
            NO_IMPLIED,
            0x69,
            NO_ACCUMULATOR,
            0x6D,
            0x7D,
            0x79,
            0x65,
            0x75,
            NO_ZEROPAGE_Y,
            NO_RELATIVE,
            NO_INDIRECT,
            0x61,
            0x71,
        ),
        InstructionDef::new(
            "and",
            NO_IMPLIED,
            0x29,
            NO_ACCUMULATOR,
            0x2D,
            0x3D,
            0x39,
            0x25,
            0x35,
            NO_ZEROPAGE_Y,
            NO_RELATIVE,
            NO_INDIRECT,
            0x21,
            0x1,
        ),
        InstructionDef::new(
            "asl",
            NO_IMPLIED,
            NO_IMMEDIATE,
            0x0A,
            0x0E,
            0x1E,
            NO_ABSOLUTE_Y,
            0x06,
            0x16,
            NO_ZEROPAGE_Y,
            NO_RELATIVE,
            NO_INDIRECT,
            NO_INDEXED_INDIRECT,
            NO_INDIRECT_INDEXED,
        ),
        InstructionDef::new(
            "bcc",
            NO_IMPLIED,
            NO_IMMEDIATE,
            NO_ACCUMULATOR,
            NO_ABSOLUTE,
            NO_ABSOLUTE_X,
            NO_ABSOLUTE_Y,
            NO_ZEROPAGE,
            NO_ZEROPAGE_X,
            NO_ZEROPAGE_Y,
            0x90,
            NO_INDIRECT,
            NO_INDEXED_INDIRECT,
            NO_INDIRECT_INDEXED,
        ),
        InstructionDef::new(
            "bcs",
            NO_IMPLIED,
            NO_IMMEDIATE,
            NO_ACCUMULATOR,
            NO_ABSOLUTE,
            NO_ABSOLUTE_X,
            NO_ABSOLUTE_Y,
            NO_ZEROPAGE,
            NO_ZEROPAGE_X,
            NO_ZEROPAGE_Y,
            0xB0,
            NO_INDIRECT,
            NO_INDEXED_INDIRECT,
            NO_INDIRECT_INDEXED,
        ),
        InstructionDef::new(
            "beq",
            NO_IMPLIED,
            NO_IMMEDIATE,
            NO_ACCUMULATOR,
            NO_ABSOLUTE,
            NO_ABSOLUTE_X,
            NO_ABSOLUTE_Y,
            NO_ZEROPAGE,
            NO_ZEROPAGE_X,
            NO_ZEROPAGE_Y,
            0xF0,
            NO_INDIRECT,
            NO_INDEXED_INDIRECT,
            NO_INDIRECT_INDEXED,
        ),
        InstructionDef::new(
            "bit",
            NO_IMPLIED,
            NO_IMMEDIATE,
            NO_ACCUMULATOR,
            0x2C,
            NO_ABSOLUTE_X,
            NO_ABSOLUTE_Y,
            0x24,
            NO_ZEROPAGE_X,
            NO_ZEROPAGE_Y,
            NO_RELATIVE,
            NO_INDIRECT,
            NO_INDEXED_INDIRECT,
            NO_INDIRECT_INDEXED,
        ),
        InstructionDef::new(
            "bmi",
            NO_IMPLIED,
            NO_IMMEDIATE,
            NO_ACCUMULATOR,
            NO_ABSOLUTE,
            NO_ABSOLUTE_X,
            NO_ABSOLUTE_Y,
            NO_ZEROPAGE,
            NO_ZEROPAGE_X,
            NO_ZEROPAGE_Y,
            0x30,
            NO_INDIRECT,
            NO_INDEXED_INDIRECT,
            NO_INDIRECT_INDEXED,
        ),
        InstructionDef::new(
            "bne",
            NO_IMPLIED,
            NO_IMMEDIATE,
            NO_ACCUMULATOR,
            NO_ABSOLUTE,
            NO_ABSOLUTE_X,
            NO_ABSOLUTE_Y,
            NO_ZEROPAGE,
            NO_ZEROPAGE_X,
            NO_ZEROPAGE_Y,
            0xD0,
            NO_INDIRECT,
            NO_INDEXED_INDIRECT,
            NO_INDIRECT_INDEXED,
        ),
        InstructionDef::new(
            "bpl",
            NO_IMPLIED,
            NO_IMMEDIATE,
            NO_ACCUMULATOR,
            NO_ABSOLUTE,
            NO_ABSOLUTE_X,
            NO_ABSOLUTE_Y,
            NO_ZEROPAGE,
            NO_ZEROPAGE_X,
            NO_ZEROPAGE_Y,
            0x10,
            NO_INDIRECT,
            NO_INDEXED_INDIRECT,
            NO_INDIRECT_INDEXED,
        ),
        InstructionDef::new(
            "brk",
            0x00,
            NO_IMMEDIATE,
            NO_ACCUMULATOR,
            NO_ABSOLUTE,
            NO_ABSOLUTE_X,
            NO_ABSOLUTE_Y,
            NO_ZEROPAGE,
            NO_ZEROPAGE_X,
            NO_ZEROPAGE_Y,
            NO_INDIRECT,
            NO_RELATIVE,
            NO_INDEXED_INDIRECT,
            NO_INDIRECT_INDEXED,
        ),
        InstructionDef::new(
            "bvc",
            NO_IMPLIED,
            NO_IMMEDIATE,
            NO_ACCUMULATOR,
            NO_ABSOLUTE,
            NO_ABSOLUTE_X,
            NO_ABSOLUTE_Y,
            NO_ZEROPAGE,
            NO_ZEROPAGE_X,
            NO_ZEROPAGE_Y,
            0x50,
            NO_INDIRECT,
            NO_INDEXED_INDIRECT,
            NO_INDIRECT_INDEXED,
        ),
        InstructionDef::new(
            "bvs",
            NO_IMPLIED,
            NO_IMMEDIATE,
            NO_ACCUMULATOR,
            NO_ABSOLUTE,
            NO_ABSOLUTE_X,
            NO_ABSOLUTE_Y,
            NO_ZEROPAGE,
            NO_ZEROPAGE_X,
            NO_ZEROPAGE_Y,
            0x70,
            NO_INDIRECT,
            NO_INDEXED_INDIRECT,
            NO_INDIRECT_INDEXED,
        ),
        InstructionDef::new(
            "clc",
            0x18,
            NO_IMMEDIATE,
            NO_ACCUMULATOR,
            NO_ABSOLUTE,
            NO_ABSOLUTE_X,
            NO_ABSOLUTE_Y,
            NO_ZEROPAGE,
            NO_ZEROPAGE_X,
            NO_ZEROPAGE_Y,
            NO_RELATIVE,
            NO_INDIRECT,
            NO_INDEXED_INDIRECT,
            NO_INDIRECT_INDEXED,
        ),
        InstructionDef::new(
            "cld",
            0xD8,
            NO_IMMEDIATE,
            NO_ACCUMULATOR,
            NO_ABSOLUTE,
            NO_ABSOLUTE_X,
            NO_ABSOLUTE_Y,
            NO_ZEROPAGE,
            NO_ZEROPAGE_X,
            NO_ZEROPAGE_Y,
            NO_RELATIVE,
            NO_INDIRECT,
            NO_INDEXED_INDIRECT,
            NO_INDIRECT_INDEXED,
        ),
        InstructionDef::new(
            "cli",
            0x58,
            NO_IMMEDIATE,
            NO_ACCUMULATOR,
            NO_ABSOLUTE,
            NO_ABSOLUTE_X,
            NO_ABSOLUTE_Y,
            NO_ZEROPAGE,
            NO_ZEROPAGE_X,
            NO_ZEROPAGE_Y,
            NO_RELATIVE,
            NO_INDIRECT,
            NO_INDEXED_INDIRECT,
            NO_INDIRECT_INDEXED,
        ),
        InstructionDef::new(
            "clv",
            0xB8,
            NO_IMMEDIATE,
            NO_ACCUMULATOR,
            NO_ABSOLUTE,
            NO_ABSOLUTE_X,
            NO_ABSOLUTE_Y,
            NO_ZEROPAGE,
            NO_ZEROPAGE_X,
            NO_ZEROPAGE_Y,
            NO_RELATIVE,
            NO_INDIRECT,
            UNUSED,
            NO_INDIRECT_INDEXED,
        ),
        InstructionDef::new(
            "cmp",
            NO_IMPLIED,
            0xC9,
            NO_ACCUMULATOR,
            0xCD,
            0xDD,
            0xD9,
            0xC5,
            0xD5,
            NO_ZEROPAGE_Y,
            NO_RELATIVE,
            NO_INDIRECT,
            0xC1,
            0xD1,
        ),
        InstructionDef::new(
            "cpx",
            NO_IMPLIED,
            0xE0,
            NO_ACCUMULATOR,
            0xEC,
            NO_ABSOLUTE_X,
            NO_ABSOLUTE_Y,
            0xE4,
            NO_ZEROPAGE_X,
            NO_ZEROPAGE_Y,
            NO_RELATIVE,
            NO_INDIRECT,
            NO_INDEXED_INDIRECT,
            NO_INDIRECT_INDEXED,
        ),
        InstructionDef::new(
            "cpy",
            NO_IMPLIED,
            0xC0,
            NO_ACCUMULATOR,
            0xCC,
            NO_ABSOLUTE_X,
            NO_ABSOLUTE_Y,
            0xC4,
            NO_ZEROPAGE_X,
            NO_ZEROPAGE_Y,
            NO_RELATIVE,
            NO_INDIRECT,
            NO_INDEXED_INDIRECT,
            NO_INDIRECT_INDEXED,
        ),
        InstructionDef::new(
            "dec",
            NO_IMPLIED,
            NO_IMMEDIATE,
            NO_ACCUMULATOR,
            0xCE,
            0xDE,
            NO_ABSOLUTE_Y,
            0xC6,
            0xD6,
            NO_ZEROPAGE_Y,
            NO_RELATIVE,
            NO_INDIRECT,
            NO_INDEXED_INDIRECT,
            NO_INDIRECT_INDEXED,
        ),
        InstructionDef::new(
            "dex",
            0xCA,
            NO_IMMEDIATE,
            NO_ACCUMULATOR,
            NO_ABSOLUTE,
            NO_ABSOLUTE_X,
            NO_ABSOLUTE_Y,
            NO_ZEROPAGE,
            NO_ZEROPAGE_X,
            NO_ZEROPAGE_Y,
            NO_RELATIVE,
            NO_INDIRECT,
            NO_INDEXED_INDIRECT,
            NO_INDIRECT_INDEXED,
        ),
        InstructionDef::new(
            "dey",
            0x88,
            NO_IMMEDIATE,
            NO_ACCUMULATOR,
            NO_ABSOLUTE,
            NO_ABSOLUTE_X,
            NO_ABSOLUTE_Y,
            NO_ZEROPAGE,
            NO_ZEROPAGE_X,
            NO_ZEROPAGE_Y,
            NO_RELATIVE,
            NO_INDIRECT,
            NO_INDEXED_INDIRECT,
            NO_INDIRECT_INDEXED,
        ),
        InstructionDef::new(
            "eor",
            NO_IMPLIED,
            0x49,
            NO_ACCUMULATOR,
            0x4D,
            0x5D,
            0x59,
            0x45,
            0x55,
            NO_ZEROPAGE_Y,
            NO_RELATIVE,
            NO_INDIRECT,
            0x41,
            0x51,
        ),
        InstructionDef::new(
            "inc",
            NO_IMPLIED,
            NO_IMMEDIATE,
            NO_ACCUMULATOR,
            0xEE,
            0xFE,
            NO_ABSOLUTE_Y,
            0xE6,
            0xF6,
            NO_ZEROPAGE_Y,
            NO_RELATIVE,
            NO_INDIRECT,
            NO_INDEXED_INDIRECT,
            NO_INDIRECT_INDEXED,
        ),
        InstructionDef::new(
            "inx",
            0xE8,
            NO_IMMEDIATE,
            NO_ACCUMULATOR,
            NO_ABSOLUTE,
            NO_ABSOLUTE_X,
            NO_ABSOLUTE_Y,
            NO_ZEROPAGE,
            NO_ZEROPAGE_X,
            NO_ZEROPAGE_Y,
            NO_RELATIVE,
            NO_INDIRECT,
            NO_INDEXED_INDIRECT,
            NO_INDIRECT_INDEXED,
        ),
        InstructionDef::new(
            "iny",
            0xC8,
            NO_IMMEDIATE,
            NO_ACCUMULATOR,
            NO_ABSOLUTE,
            NO_ABSOLUTE_X,
            NO_ABSOLUTE_Y,
            NO_ZEROPAGE,
            NO_ZEROPAGE_X,
            NO_ZEROPAGE_Y,
            NO_RELATIVE,
            NO_INDIRECT,
            NO_INDEXED_INDIRECT,
            NO_INDIRECT_INDEXED,
        ),
        InstructionDef::new(
            "jmp",
            NO_IMPLIED,
            NO_IMMEDIATE,
            NO_ACCUMULATOR,
            0x4C,
            NO_ABSOLUTE_X,
            NO_ABSOLUTE_Y,
            NO_ZEROPAGE,
            NO_ZEROPAGE_X,
            NO_ZEROPAGE_Y,
            NO_RELATIVE,
            0x6C,
            NO_INDEXED_INDIRECT,
            NO_INDIRECT_INDEXED,
        ),
        InstructionDef::new(
            "jsr",
            NO_IMPLIED,
            NO_IMMEDIATE,
            NO_ACCUMULATOR,
            0x20,
            NO_ABSOLUTE_X,
            NO_ABSOLUTE_Y,
            NO_ZEROPAGE,
            NO_ZEROPAGE_X,
            NO_ZEROPAGE_Y,
            NO_RELATIVE,
            NO_INDIRECT,
            NO_INDEXED_INDIRECT,
            NO_INDIRECT_INDEXED,
        ),
        InstructionDef::new(
            "lda",
            NO_IMPLIED,
            0xA9,
            NO_ACCUMULATOR,
            0xAD,
            0xBD,
            0xB9,
            0xA5,
            0xB5,
            NO_ZEROPAGE_Y,
            NO_RELATIVE,
            NO_INDIRECT,
            0xA1,
            0xB1,
        ),
        InstructionDef::new(
            "ldx",
            NO_IMPLIED,
            0xA2,
            NO_ACCUMULATOR,
            0xAE,
            NO_ABSOLUTE_X,
            0xBE,
            0xA6,
            NO_ZEROPAGE_X,
            0xB6,
            NO_RELATIVE,
            NO_INDIRECT,
            NO_INDEXED_INDIRECT,
            NO_INDIRECT_INDEXED,
        ),
        InstructionDef::new(
            "ldy",
            NO_IMPLIED,
            0xA0,
            NO_ACCUMULATOR,
            0xAC,
            0xBC,
            NO_ABSOLUTE_Y,
            0xA4,
            0xB4,
            NO_ZEROPAGE_Y,
            NO_RELATIVE,
            NO_INDIRECT,
            NO_INDEXED_INDIRECT,
            NO_INDIRECT_INDEXED,
        ),
        InstructionDef::new(
            "lsr",
            NO_IMPLIED,
            NO_IMMEDIATE,
            0x4A,
            0x4E,
            0x5E,
            NO_ABSOLUTE_Y,
            0x46,
            0x56,
            NO_ZEROPAGE_Y,
            NO_RELATIVE,
            NO_INDIRECT,
            NO_INDEXED_INDIRECT,
            NO_INDIRECT_INDEXED,
        ),
        InstructionDef::new(
            "nop",
            0xEA,
            NO_IMMEDIATE,
            NO_ACCUMULATOR,
            NO_ABSOLUTE,
            NO_ABSOLUTE_X,
            NO_ABSOLUTE_Y,
            NO_ZEROPAGE,
            NO_ZEROPAGE_X,
            NO_ZEROPAGE_Y,
            NO_RELATIVE,
            NO_INDIRECT,
            NO_INDEXED_INDIRECT,
            NO_INDIRECT_INDEXED,
        ),
        InstructionDef::new(
            "ora",
            NO_IMPLIED,
            0x09,
            NO_ACCUMULATOR,
            0x0D,
            0x1D,
            0x19,
            0x05,
            0x15,
            NO_ZEROPAGE_Y,
            NO_RELATIVE,
            NO_INDIRECT,
            0x01,
            0x11,
        ),
        InstructionDef::new(
            "pha",
            0x48,
            NO_IMMEDIATE,
            NO_ACCUMULATOR,
            NO_ABSOLUTE,
            NO_ABSOLUTE_X,
            NO_ABSOLUTE_Y,
            NO_ZEROPAGE,
            NO_ZEROPAGE_X,
            NO_ZEROPAGE_Y,
            NO_RELATIVE,
            NO_INDIRECT,
            NO_INDEXED_INDIRECT,
            NO_INDIRECT_INDEXED,
        ),
        InstructionDef::new(
            "php",
            0x08,
            NO_IMMEDIATE,
            NO_ACCUMULATOR,
            NO_ABSOLUTE,
            NO_ABSOLUTE_X,
            NO_ABSOLUTE_Y,
            NO_ZEROPAGE,
            NO_ZEROPAGE_X,
            NO_ZEROPAGE_Y,
            NO_RELATIVE,
            NO_INDIRECT,
            NO_INDEXED_INDIRECT,
            NO_INDIRECT_INDEXED,
        ),
        InstructionDef::new(
            "pla",
            0x68,
            NO_IMMEDIATE,
            NO_ACCUMULATOR,
            NO_ABSOLUTE,
            NO_ABSOLUTE_X,
            NO_ABSOLUTE_Y,
            NO_ZEROPAGE,
            NO_ZEROPAGE_X,
            NO_ZEROPAGE_Y,
            NO_RELATIVE,
            NO_INDIRECT,
            NO_INDEXED_INDIRECT,
            NO_INDIRECT_INDEXED,
        ),
        InstructionDef::new(
            "plp",
            0x28,
            NO_IMMEDIATE,
            NO_ACCUMULATOR,
            NO_ABSOLUTE,
            NO_ABSOLUTE_X,
            NO_ABSOLUTE_Y,
            NO_ZEROPAGE,
            NO_ZEROPAGE_X,
            NO_ZEROPAGE_Y,
            NO_RELATIVE,
            NO_INDIRECT,
            NO_INDEXED_INDIRECT,
            NO_INDIRECT_INDEXED,
        ),
        InstructionDef::new(
            "rol",
            NO_IMPLIED,
            NO_IMMEDIATE,
            0x2A,
            0x2E,
            0x3E,
            NO_ABSOLUTE_Y,
            0x26,
            0x36,
            NO_ZEROPAGE_Y,
            NO_RELATIVE,
            NO_INDIRECT,
            NO_INDEXED_INDIRECT,
            NO_INDIRECT_INDEXED,
        ),
        InstructionDef::new(
            "ror",
            NO_IMPLIED,
            NO_IMMEDIATE,
            0x6A,
            0x6E,
            0x7E,
            NO_ABSOLUTE_Y,
            0x66,
            0x76,
            NO_ZEROPAGE_Y,
            NO_RELATIVE,
            NO_INDIRECT,
            NO_INDEXED_INDIRECT,
            NO_INDIRECT_INDEXED,
        ),
        InstructionDef::new(
            "rti",
            0x40,
            NO_IMMEDIATE,
            NO_ACCUMULATOR,
            NO_ABSOLUTE,
            NO_ABSOLUTE_X,
            NO_ABSOLUTE_Y,
            NO_ZEROPAGE,
            NO_ZEROPAGE_X,
            NO_ZEROPAGE_Y,
            NO_RELATIVE,
            NO_INDIRECT,
            NO_INDEXED_INDIRECT,
            NO_INDIRECT_INDEXED,
        ),
        InstructionDef::new(
            "rts",
            0x60,
            NO_IMMEDIATE,
            NO_ACCUMULATOR,
            NO_ABSOLUTE,
            NO_ABSOLUTE_X,
            NO_ABSOLUTE_Y,
            NO_ZEROPAGE,
            NO_ZEROPAGE_X,
            NO_ZEROPAGE_Y,
            NO_RELATIVE,
            NO_INDIRECT,
            NO_INDEXED_INDIRECT,
            NO_INDIRECT_INDEXED,
        ),
        InstructionDef::new(
            "sbc",
            NO_IMPLIED,
            0xE9,
            NO_ACCUMULATOR,
            0xED,
            0xFD,
            0xF9,
            0xE5,
            0xF5,
            NO_ZEROPAGE_Y,
            NO_RELATIVE,
            NO_INDIRECT,
            0xE1,
            0xF1,
        ),
        InstructionDef::new(
            "sec",
            0x38,
            NO_IMMEDIATE,
            NO_ACCUMULATOR,
            NO_ABSOLUTE,
            NO_ABSOLUTE_X,
            NO_ABSOLUTE_Y,
            NO_ZEROPAGE,
            NO_ZEROPAGE_X,
            NO_ZEROPAGE_Y,
            NO_RELATIVE,
            NO_INDIRECT,
            NO_INDEXED_INDIRECT,
            NO_INDIRECT_INDEXED,
        ),
        InstructionDef::new(
            "sed",
            0xF8,
            NO_IMMEDIATE,
            NO_ACCUMULATOR,
            NO_ABSOLUTE,
            NO_ABSOLUTE_X,
            NO_ABSOLUTE_Y,
            NO_ZEROPAGE,
            NO_ZEROPAGE_X,
            NO_ZEROPAGE_Y,
            NO_RELATIVE,
            NO_INDIRECT,
            NO_INDEXED_INDIRECT,
            NO_INDIRECT_INDEXED,
        ),
        InstructionDef::new(
            "sei",
            0x78,
            NO_IMMEDIATE,
            NO_ACCUMULATOR,
            NO_ABSOLUTE,
            NO_ABSOLUTE_X,
            NO_ABSOLUTE_Y,
            NO_ZEROPAGE,
            NO_ZEROPAGE_X,
            NO_ZEROPAGE_Y,
            NO_RELATIVE,
            NO_INDIRECT,
            NO_INDEXED_INDIRECT,
            NO_INDIRECT_INDEXED,
        ),
        InstructionDef::new(
            "sta",
            NO_IMPLIED,
            NO_IMMEDIATE,
            NO_ACCUMULATOR,
            0x8D,
            0x9D,
            0x99,
            0x85,
            0x95,
            NO_ZEROPAGE_Y,
            NO_RELATIVE,
            NO_INDIRECT,
            0x81,
            0x91,
        ),
        InstructionDef::new(
            "stx",
            NO_IMPLIED,
            NO_IMMEDIATE,
            NO_ACCUMULATOR,
            0x8E,
            NO_ABSOLUTE_X,
            NO_ABSOLUTE_Y,
            0x86,
            NO_ZEROPAGE_X,
            0x96,
            NO_RELATIVE,
            NO_INDIRECT,
            NO_INDEXED_INDIRECT,
            NO_INDIRECT_INDEXED,
        ),
        InstructionDef::new(
            "sty",
            NO_IMPLIED,
            NO_IMMEDIATE,
            NO_ACCUMULATOR,
            0x8C,
            NO_ABSOLUTE_X,
            NO_ABSOLUTE_Y,
            0x84,
            0x94,
            NO_ZEROPAGE_Y,
            NO_RELATIVE,
            NO_INDIRECT,
            NO_INDEXED_INDIRECT,
            NO_INDIRECT_INDEXED,
        ),
        InstructionDef::new(
            "tax",
            0xAA,
            NO_IMMEDIATE,
            NO_ACCUMULATOR,
            NO_ABSOLUTE,
            NO_ABSOLUTE_X,
            NO_ABSOLUTE_Y,
            NO_ZEROPAGE,
            NO_ZEROPAGE_X,
            NO_ZEROPAGE_Y,
            NO_RELATIVE,
            NO_INDIRECT,
            NO_INDEXED_INDIRECT,
            NO_INDIRECT_INDEXED,
        ),
        InstructionDef::new(
            "tay",
            0xA8,
            NO_IMMEDIATE,
            NO_ACCUMULATOR,
            NO_ABSOLUTE,
            NO_ABSOLUTE_X,
            NO_ABSOLUTE_Y,
            NO_ZEROPAGE,
            NO_ZEROPAGE_X,
            NO_ZEROPAGE_Y,
            NO_RELATIVE,
            NO_INDIRECT,
            NO_INDEXED_INDIRECT,
            NO_INDIRECT_INDEXED,
        ),
        InstructionDef::new(
            "tsx",
            0xBA,
            NO_IMMEDIATE,
            NO_ACCUMULATOR,
            NO_ABSOLUTE,
            NO_ABSOLUTE_X,
            NO_ABSOLUTE_Y,
            NO_ZEROPAGE,
            NO_ZEROPAGE_X,
            NO_ZEROPAGE_Y,
            NO_RELATIVE,
            NO_INDIRECT,
            NO_INDEXED_INDIRECT,
            NO_INDIRECT_INDEXED,
        ),
        InstructionDef::new(
            "txa",
            0x8A,
            NO_IMMEDIATE,
            NO_ACCUMULATOR,
            NO_ABSOLUTE,
            NO_ABSOLUTE_X,
            NO_ABSOLUTE_Y,
            NO_ZEROPAGE,
            NO_ZEROPAGE_X,
            NO_ZEROPAGE_Y,
            NO_RELATIVE,
            NO_INDIRECT,
            NO_INDEXED_INDIRECT,
            NO_INDIRECT_INDEXED,
        ),
        InstructionDef::new(
            "txs",
            0x9A,
            NO_IMMEDIATE,
            NO_ACCUMULATOR,
            NO_ABSOLUTE,
            NO_ABSOLUTE_X,
            NO_ABSOLUTE_Y,
            NO_ZEROPAGE,
            NO_ZEROPAGE_X,
            NO_ZEROPAGE_Y,
            NO_RELATIVE,
            NO_INDIRECT,
            NO_INDEXED_INDIRECT,
            NO_INDIRECT_INDEXED,
        ),
        InstructionDef::new(
            "tya",
            0x98,
            NO_IMMEDIATE,
            NO_ACCUMULATOR,
            NO_ABSOLUTE,
            NO_ABSOLUTE_X,
            NO_ABSOLUTE_Y,
            NO_ZEROPAGE,
            NO_ZEROPAGE_X,
            NO_ZEROPAGE_Y,
            NO_RELATIVE,
            NO_INDIRECT,
            NO_INDEXED_INDIRECT,
            NO_INDIRECT_INDEXED,
        ),
    ]
}
